---
- hosts: webservers
  become: true
  tasks:
    - name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: html/index.html
        dest: /var/www/html/
...
